#pragma once

#include "nodes/assignment_operator.h"
#include "nodes/ASTNode.h"
#include "nodes/binary_operator.h"
#include "nodes/body.h"
#include "nodes/cast.h"
#include "nodes/dot_operator.h"
#include "nodes/dowhile.h"
#include "nodes/else.h"
#include "nodes/expression.h"
#include "nodes/for.h"
#include "nodes/function.h"
#include "nodes/functioncall.h"
#include "nodes/identifier.h"
#include "nodes/if.h"
#include "nodes/literal.h"
#include "nodes/loopcontrol.h"
#include "nodes/operator.h"
#include "nodes/parameter.h"
#include "nodes/return.h"
#include "nodes/struct.h"
#include "nodes/type.h"
#include "nodes/unary_operator.h"
#include "nodes/variable.h"
#include "nodes/while.h"

